### PR TITLE
Support Redfish on IBM POWER servers (returns 200 upon successful auth)

### PR DESCRIPTION
**Pull request by xray-sky**
This change addresses https://github.com/xlab-si/redfish-client-ruby/issues/44

### CODE REVIEW

**Comment by tadeboro** [comment]
I already expressed my feeling towards the vendor-specific hacks [here](https://github.com/xlab-si/redfish-client-ruby/issues/32#issuecomment-479590222). And to be completely honest, I would much rather see that IBM fixes their Redfish implementation. Redfish specification is quite clear about the valid status codes on data modification requests: http://redfish.dmtf.org/schemas/DSP0266_1.9.0.html#modification-success-responses

Why am I such a pain in the ass? Because it will be almost impossible to remove those hacks once they are in. Also, adding such hacks into the library removes the incentive for vendors to fix their implementations because things work as far as they are concerned.

Did you try talking about this with your hardware provider?

**Comment by xray-sky** [comment]
The other way of looking at it is that a library that doesn't work in the real world is not very useful. I really like the way you've abstracted the API into object methods, which is supremely helpful when every vendor has a completely different set of endpoint URLs. It makes the libraries the vendors supply that hardcode every possible request and only work with their own machines look like the shabby first year CS hacks they are.

I saw your other comment. I felt like accepting 200 in addition to 201 in this specific circumstance was not much of a compromising of principles. There is at least one other place in the code where you're already accepting multiple success responses. For what it's worth, the standard says "should" and not "must", and this is the sort of thing that results. Section 8.3 describes the meaning of a 200 response code for Redfish and it reasonably applies. But you're the package maintainer, you get to decide. Take it or don't.

**Comment by xray-sky** [comment]
What I mean is, I never felt like you were under any obligation to accept this pull request. It's a proposal; that's all.

**Comment by tadeboro** [comment]
The PR in the current form definitely cannot be included in the repo. It is missing a meaningful commit message explaining why this hack was added, and a unit test that makes sure we do accept 200 when logging in.

We tested this library on quite a few systems (Dells, HPEs, SuperMicros, Lenovos) and it works perfectly there. So saying that the library does not work in the real world is a bit dishonest. It definitely does not work on all systems, but usually, there is a good reason behind this.

But you failed to respond to my question about talking to your vendor about this. Because you should at least file a bug so that someone knows things are broken.

While we were developing this library, we also talked to some vendors about the incompatibilities with Redfish Specification that we found and they actually fixed them. Adding a hack to the library should be your backup plan if the vendor does not respond.

**Comment by xray-sky** [comment]
"Doesn't work in the real world" was not meant to impugn your efforts - I simply meant the real world presents imperfections from time to time. It definitely does not work with IBM POWER systems we actually have. The whole reason I even suggested the change is because the library already works so well with the mix of other vendors' systems we actually have. 

I will gladly make the other changes you requested if it will make the difference in whether the PR is accepted or not. My time would be better spent on other projects if not. You are correct that I haven't yet opened a bug with IBM about it. I'm not opposed to it, and in fact I give 50/50 odds that it might (eventually) get fixed, which is pretty good by IBM standards. But I'm not even twelve hours into this yet.

**Comment by tadeboro** [comment]
If IBM says that it will not fix this issue, I will merge this PR.

If having this "fix" upstream would make your life easier, I am prepared to merge this as soon as the test is prepared and make a new release. But I have one condition: you will file another PR that removes this hack if IBM releases a fix for ther firmware. Sounds fair?

**Comment by xray-sky** [comment]
My primary concern was that IBM takes 15, 18, 24 months to deliver a firmware version that includes a fix and we're hooped that whole time (they might not, but they have at times in the past). I might take a couple days to sort that all out, but this seems like a workable path forward to me. 

An immediate fix isn't necessary; the long pole for our use case is actually a separate pull request I'm working through the Foreman project to add redfish support there (implemented on top of this library). Judging by what I can observe of your release cycle, we can reasonably wait until the next one.

I am a little confused about your comment re: the commit message though.

**Comment by tadeboro** [comment]
I usually mandate that the commit messages follow the structure described at https://chris.beams.io/posts/git-commit/ For example, [this](https://github.com/xlab-si/redfish-client-ruby/commit/80dd96ccc9dfae5ceafd395d7252fc411c130293) and [this](https://github.com/xlab-si/redfish-client-ruby/commit/663bedb1537558a272f3adb7a5a74ff1a06a27e8) are two examples from this repository.

In this case, I would expect the message to include what Redfish standard expects and what IBM's BMC returns.

**Comment by xray-sky** [comment]
We have a PMR from IBM - I'm not sure it's visible outside our account, but I'll mention it: PMR 22674,T11,000. Let me get through the first couple back-and-forths of "does hardware or software support own this PMR" and I'll have a better sense of where it's likely to go from here.

**Comment by xray-sky** [comment]
I was holding off any updates on the PR until I got a sense of what IBM's response to the PMR would be like. After some delay getting it assigned to Engineering, today I got an update from IBM that they plan to correct this in their next set of firmware fixpacks.

**Comment by vwbusguy** [comment]
It appears that Cisco does the same thing (returns 200 instead of 201): http://talk.manageiq.org/t/error-in-adding-redfish-supported-cisco-imc-server-in-manageiq/4633/8

**Comment by xray-sky** [comment]
IBM reports the issue corrected in POWER9 firmware https://delivery04.dhe.ibm.com/sar/CMA/SFA/095bw/0/01VL940_061_027.html

I haven't tested this yet but don't have any reason to doubt it's fixed.

POWER8 fix still promised.

**Comment by xray-sky** [comment]
IBM reports the issue corrected in POWER8 firmware https://download4.boulder.ibm.com/sar/CMA/SFA/09cjs/0/01SV860_226_165.html

I haven't tested this yet but don't have any reason to doubt it's fixed.

My original problem has been adequately addressed by the vendor; abandoning PR.

**Pull request closed without merging**
